### ISSUE TITLE
Left and right vertical vane (swing)

### ISSUE THREAD

**Issue by espenjohannessen** [XattSPT/com.melcloud#20] opened 2020-11-23 21:03 UTC
Just to set the scene: I have a Kaiteki 6600 mounted in between two floors, in the stairway, and use the two separate vertical vanes to direct air both up and down. When the temperature on the main floor is above 21 degrees I would like the hot airstream to be split between the two floors (left vane up, right vane down), but when the temperature on the main floor drops below 21 degrees I would like the hot airstream to only be pushed into the main floor (both vanes up) to heat it up as quickly as possible.

I see flow cards for vertical and horizontal vanes (swings), but I can't find a way to control the right and left vertical vanes separately. Have I missed something? And if not; is this something that can be added?

**Comment by XattSPT** [comment] 2020-11-23 21:09
Hi @espenjohannessen if you want to share ur device (melcloud) with me I can try to investigate which data is on theese type of devices and if it is possible to control separately from melcloud. 

If you are interested I will share my email with you and you can add me as a guest on melcloud app. 

I can try to update the app if data is available.

**Comment by espenjohannessen** [comment] 2020-11-23 21:16
Sure, just send me your email and I'll add you in MelCloud.

**Comment by espenjohannessen** [comment] 2020-11-23 21:18
![image](https://user-images.githubusercontent.com/3808959/100016367-97087880-2dd9-11eb-81bf-164fded9097a.png)

**Comment by XattSPT** [comment] 2020-11-23 21:20
@espenjohannessen gerard.ricart@gmail.com

**Comment by espenjohannessen** [comment] 2020-11-23 21:22
Based on the UI in MelCloud I suspect it's not supported, but I'll still add you so you can take a look!

**Comment by XattSPT** [comment] 2020-11-23 21:24
Sure! I’ll take a look and come back to you. 

There are some hide functions on melcloud that depends on device, so better to take a look before to discard!

**Comment by espenjohannessen** [comment] 2020-11-23 21:33
Awesome, thanks! I'll also add a picture of the remote, where you can see the buttons for configuring the horizontal vane as one and the vertical as left and right.

**Comment by espenjohannessen** [comment] 2020-11-23 21:41
![2020-11-23 22 31 37](https://user-images.githubusercontent.com/3808959/100018653-13e92180-2ddd-11eb-95a9-981f9d30f757.jpg)

**Comment by espenjohannessen** [comment] 2020-11-23 22:25
I've looked through the data returned by the API, and also a couple of other integrations and forum posts I've found, and it does unfortunately look like there's currently no support for left and right vertical vanes in MelCloud. There is only one property associated with the vertical vane, "VaneVertical", and it can only be set between 0 (auto), 1-6 (angle) and 7 (swing).

I sent an email to the local customer support, asking them to dig into this and see if there are any plans to add this functionality to MelCloud, but honestly I'll be surprised if I even hear back from them at all.

**Comment by espenjohannessen** [comment] 2020-11-24 01:39
I should also mention that during my testing I've found a couple of issues:

* VaneHorizontal is not correctly mapped and it's value gets overwritten on each device update if it's set to 8 or 12. It should go between 0 (auto), 1-5 (angles), 8 (50/50 split left and right) and 12 (swing)

* VaneVertical seems to always show the left vane, but update both, so any changes I make to the right vane with the remote gets overwritten on each device update. I was planning on using Homey to control the temperature, even if the individual vanes couldn't be controlled, but with this issue that's not really an option since I'm no longer able to split the hot airstream between the two floors. If we're not able to solve the issue of addressing each vane individually then perhaps you could add something as simple as a setting to ignore the vertical vane altogether?

I'll also link in a couple of repos I found for future reference:
* https://github.com/Black-Thunder/ioBroker.melcloud
* https://github.com/vilppuvuorinen/pymelcloud

**Comment by XattSPT** [comment] 2020-11-28 17:17
dear @espenjohannessen, thanks for your corrections, I'll be finishing some adjustements and will publish the next version. 

regarding Vane vertical, I've been cheching data available and there is no data regarding this funcion. 

If you see anyone else ho has implemented, please tell me and we can copy that if it's available :D

**Comment by XattSPT** [comment] 2020-11-28 22:07
untill publishing, you can try a test version there:

https://homey.app/a/com.mecloud/test/

**Comment by ketillund** [comment] 2020-11-29 10:03
> I sent an email to the local customer support, asking them to dig into this and see if there are any plans to add this functionality to MelCloud, but honestly I'll be surprised if I even hear back from them at all.

I was in contact with the Norwegian customer support in the beginning of August, and I actually got a response! The reason for contacting them was that the MelCloud app only allows you to control the horizontal vanes individually, not the vertical ones, and I asked if this would be added to the app soon. The response I got was this (my translation):

"It will become possible to control the vertical vanes individually, but we haven't got a release date for this. There are some big changes to happen in 2020 before this is given priority. Everything has been put on hold since the pandemic hit the world in March. But you can be sure that in 2021 a lot will be coming :)"

So it seems it might be a lot of changes to MelCloud in the near future. I really hope it will be possible to control the vanes indiviually, also from Homey.

**Comment by espenjohannessen** [comment] 2020-11-30 10:52
@ketillund I got a similar response myself, from Daniel waaay outside office hours, so I guess I owe the Norwegian customer support and Daniel in particular an apology ;D

Hopefully the latest changes, including the pull request that Gerard merged a couple of days ago, should make the current functionality in MelCloud reliably available through Homey.

I currently have 4 flows running related to the AC, adjusting both vertical vanes, horizontal vanes and temperature based on a separate temperature sensor on the main floor, to split air between the main floor and basement. The idea is to prioritize the main floor and only split the hot air between the two floors when the temperature is above a set threshold.

I'll post an update here when I've had everything running for a few days on the latest version.

**Comment by espenjohannessen** [comment] 2020-11-30 11:15
@XattSPT I haven't seen anyone implement separate vertical vanes, and MelCloud has also confirmed that it's not currently supported, so I think we'll have to let that go for now.

One other thing that caught my attention when comparing your code with the other repos I've found is that everyone else are only changing ONE property at the time and are using different EffectiveFlags for the different changes. Could this explain why some users are experiencing periodic and hard to pin down issues? As an example I see the following EffectiveFlags in ioBroker:

exports.DeviceOperationModes = Object.freeze({
	UNDEF: { value: -1, effectiveFlags: -1 },
	HEAT: { value: 1, effectiveFlags: 1 + 2 },
	DRY: { value: 2, effectiveFlags: 1 + 2 },
	COOL: { value: 3, effectiveFlags: 1 + 2 },
	VENT: { value: 7, effectiveFlags: 1 + 2 },
	AUTO: { value: 8, effectiveFlags: 1 + 2 }
});

exports.DevicePowerStates = Object.freeze({
	OFF: { value: false, effectiveFlags: 1 },
	ON: { value: true, effectiveFlags: 1 },
});

exports.DeviceOptions = Object.freeze({
	PowerState: { id: "PowerState" },
	TargetHeatingCoolingState: { id: "TargetHeatingCoolingState" },
	TargetTemperature: { id: "TargetTemperature", effectiveFlags: 4 },
	FanSpeed: { id: "FanSpeed", effectiveFlags: 8 },
	VaneHorizontalDirection: { id: "VaneHorizontalDirection", effectiveFlags: 256 },
	VaneVerticalDirection: { id: "VaneVerticalDirection", effectiveFlags: 16 }
});

**Comment by XattSPT** [comment] 2020-11-30 12:13
@espenjohannessen , I sent all parameters together and use efeectiveflags to check all info.

let me explain: 
 - if you change on/off efectiveflag is 1
 - if you change mode, efectiveflag is 2 (so they sent 1 for on/off and 2 for mode), read 3

so effectiveflags are comulative.

Other way is make Melcloud check all parameters (bigger cumulative effectiveflags number), and melcloud update only information that is provided in the .json send.

this way is programatically more easy, and reduce number of queries sent to melcloud. This second point is important because Melcloud has a numer of daily queries you can make, so if you do them so much often and you have several devices, at the end of a day it could not be responding. 

At the end is only different approach, I done like you found at the beginning, and later discovered the way is done now. I think this way allows me to add funcions and go ahed on develing new funcions as they are added, without going back to comunication module every change. 

Post-note: in AC devices is easier than in eat-pumps devices, there is a lot more effective flags and characterisitcs, so using each effectiveflag individually is complicated (and some effectiveflags number are not discovered).

**Comment by espenjohannessen** [comment] 2020-11-30 12:23
@XattSPT Ah, I see and agree! That sounds a lot more efficient, but are you sure setting effectiveFlags to 31 covers all cases? Since VaneHorizontalDirection uses 256 I would assume that it's not catched when always using 31? I'll do some testing with the new version you've just published later over the next few days and report my findings back to you : )

**Comment by XattSPT** [comment] 2020-11-30 18:34
I saw that 01xF updates all (al least as I can see in other develpments)... but my device do not have moving Hvanes :D so I could not try it at all... 

If you have and can test it will be best way to be sure.

If do not works properly I suggest to use 256+31 if it works...

Thanks in advance!

**Comment by espenjohannessen** [comment] 2020-12-02 08:06
@XattSPT It's definitely not working as expected and after A LOT of testing through Postman I still have no idea exactly what's going on. At first it looks like the change has taken effect when I run "/User/ListDevices" or"/Device/Get" immediately after "/Device/SetAta", but as soon as the NextCommunication datetime has passed, one or more of the values gets reset.

I did notice this comment in the pymelcloud repo, but I haven't been able to reproduce this exact behaviour either: "There's weird behavior associated with the horizontal vane swing. Toggling it on will also toggle vertical swing on and the horizontal swing has to be disabled before vertical vanes can be adjusted to any other position. This behavior can be replicated using the MELCloud user inteface."

I've literally made hundreds of Postman calls trying to figure this out and I'm close to just giving up now. Perhaps there's a good reason why the other repos are only making one change per request?

**Comment by OlivierZal** [comment] 2022-09-30 15:34
All these issues have been fixed in the latest version of the app. Don’t hesitate to raise any new issue in case of unexpected behavior. Regards

**Closed by OlivierZal** 2022-09-30 15:34 UTC
